Fix nil upcase on startup
bloomberg/cartodb pull request #136
Opened 2017-02-21 11:30 UTC by gfiorav

##Context

A debug trace present in the HTTP header, asked for `ActionDispatch::Http::Headers#[nil]`. This results in an error trace:

```
NoMethodError (undefined method `upcase' for nil:NilClass):
  lib/carto/http_header_authentication.rb:81:in `header_value'
  lib/carto/http_header_authentication.rb:9:in `valid?'
  app/controllers/application_controller.rb:363:in `http_header_authentication?'
```

This PR provides a safety check where `ActionDispatch::Http::Headers#[possible_nil]` is only attempted if `possible_nil` is `.present?`, which means that it's neither `nil` (null) or `''` (empty string).

If the trace is still useful and must be kept (it doesn't provide much info), this check can be used to not generate the error when rendering it.

2017-02-21 14:38 UTC, vishalya requested changes

2017-02-21 14:38 UTC, vishalya commented on lib/carto/http_header_authentication.rb
> +      headers[header] if header.present?
We need the logs for the 'user-auto-creation', as it traces the request for the user authentication and auto-creation. the idea is that, if you search the logs for 'user-auto-creation, it should give the flow of the request - if something fails. You can either put this logging back or come up with a better solution. I agree, it looks ugly, but it serves a useful purpose.

2017-02-21 14:38 UTC, vishalya commented on spec/lib/carto/http_header_authentication_spec.rb
> +    it 'resists when config header is nil' do
What's the command you run to test it? 
Also, are you able to kick off the auto-testing inside the VM? Please give me the command if you are able to do it?

2017-02-21 14:46 UTC, gfiorav commented on spec/lib/carto/http_header_authentication_spec.rb
> +    it 'resists when config header is nil' do
Sure!

RAILS runs tests in separate environment, `test`, that has to be migrated like the `development` or `production` environments. We provide a scrip in the `Makefile` for running all tests:

```
make check
```

This will create your testing DBs and migrate the to the latest schema before running all specs.

Manually, you'd do:
```
RAILS_ENV=test bundle exec rails db:drop
RAILS_ENV=test bundle exec rails db:create
RAILS_ENV=test bundle exec rails db:migrate
```

Now your testing environment is ready. Please be aware of the `RAILS_ENV=test`, if you don't specify it, `RAILS_ENV=development` is the default and it will wipe your db in `development`.

Now, to run any single spec (this one for exapmple), simply:
```
bundle exec rspec spec/lib/carto/http_header_authentication_spec.rb -e "resists when config header is nil"
```

Note that we don't specify the environment since the `rspec` gem sets `test` by default. You can also specify the line number where the test is at instead of its name.

2017-02-21 14:49 UTC, gfiorav commented on lib/carto/http_header_authentication.rb
> +      headers[header] if header.present?
We do this by logging NGINX requests. We then query them with Elastic Search / Kibana.

Please be aware that you shouldn't trust these flows, since when multithreading, some messages might not make it to stdout.

2017-02-21 14:50 UTC, gfiorav commented on lib/carto/http_header_authentication.rb
> +      headers[header] if header.present?
In the mean time, I'm putting the log back in. Do you need the values or were those for debugging? It be simpler to put `user-auto-creation : Trying to extract value from headers`, no interpolation needed.

What do you think?

2017-02-21 16:32 UTC, vishalya commented on lib/carto/http_header_authentication.rb
> +      headers[header] if header.present?
yes, that should be good.

2017-02-21 16:39 UTC, gfiorav commented
Hey @vishalya, I added the logging back in.

See if it's good enough :)

2017-02-21 17:39 UTC, vishalya commented
I would like to see the values `for #{header}, value is #{headers[header]}"` if they are available... else simply hardcode to `Not available`

2017-02-21 18:05 UTC, gfiorav commented
Ok. Btw, what do you think about the multithreading issue?

Also, we use this for logging: lib/carto/http_header_authentication.rb

In production it works with Rollbar but locally it prints to std out.

Question: what do you parse to get these messages? `log/<environment>.log`?

2017-02-21 18:32 UTC, vishalya commented
Regarding multithreading, it's not complete. Logging is work in progress.
They we work with logs in production is that - we collect all the logs from all the servers (nginx, rails, windshaft/sql api etc.) to kibana logstash and then we search for a key... in this auto-user-creation it will be the username and see if there are any issues.

2017-02-22 13:57 UTC, gfiorav commented
Ok @vishalya, I think it's how you want it now

2017-02-22 14:37 UTC, vishalya commented
Looks good, thanks, I will merge it after a round of integration testing, for the next sprint.

2017-03-17 10:56 UTC, gfiorav commented
@vishalya since I see conflicts have appeared... is this still on course to being merged?

2017-03-17 13:19 UTC, vishalya commented
I think, Mehmet might have merged it, if it was a part of any other PR, Let me check with him and get back to you.

2017-03-28 15:35 UTC, gfiorav commented
Can we please merge this into blp_dev 🙏 !

2017-08-10 18:58 UTC, gfiorav commented
Closing due to inactivity

2017-08-10 18:58 UTC, closed without merging