Adding check for a valid user
bloomberg/cartodb pull request #198
Opened 2017-07-17 19:43 UTC by vishalya

This is to guard against the orphaned visualization records. i.e. visualizations without any associated owners (users)

2017-07-18 10:24 UTC, gfiorav requested changes
Hey Vishal, I made some comments. However, I don't know why you're adding these checks. I would advise you not to, since it's a significant flow change.

If you can explain the issue, maybe we can come up with an alternative solution. This seems too much change... we would have noticed at CARTO.

2017-07-18 10:24 UTC, gfiorav commented on app/models/table.rb
> +      CartoDB.notify_error("get_all_by_names user doesn't exist")
Use the new logger:

```ruby
CartoDB::Logger.error(message: 'get_all_by_names user doesn't exist')
```

2017-07-18 10:24 UTC, gfiorav commented on app/models/table.rb
> +      CartoDB.notify_error("get_all_by_names user doesn't exist")
Same here

2017-07-18 10:24 UTC, gfiorav commented on app/models/table/privacy_manager.rb
> +          CartoDB.notify_error("Visualization user doesn't exist", visualization_id: visualization.id)
Same here

2017-07-18 10:24 UTC, gfiorav commented on app/models/visualization/member.rb
> +          return self;
Remove the `;` and use the new logger

2017-07-18 11:54 UTC, vishalya commented
The root cause is that - we do have the visualizations in the db with no associated user. 
I think - all visualizations should have an user associated with it. If that's the case, then these checks are just the guard against those 'inconsistent data records'. Without these checks flow just breaks some point later.
Deleting the orphaned records is way too destructive and also doesn't really guarantee that there won't be any future inconsistency, unless we add some database level integrity. 
My suspicion is that, the `user:deletion:by_username` sometimes fails, at least for our flow with the fwd based data library. 
I am keeping this 'fix' ready, since it solves the sync issue on QA,

2017-07-18 12:29 UTC, gfiorav commented
I'd search the root cause of the orphaned visualisations then! How does this happen? It shouldn't. 

If this is happening there is something off and it's better to take care of it now.

2017-07-18 12:40 UTC, vishalya commented
I had seen some issues, with the `user:deletion:by_username`, I will look into that as well. But my point is that - these changes are harmless if the user exists. The flow will continue & if user doesn't exists, then it's going to fail somewhere at a later stage.
Also, do you see any orphaned visulization records in your QA/Prod?

2017-07-18 12:42 UTC, gfiorav commented
Yeah, in that sense this is ok, but only as a "debug trace". IMO this only makes sense as a step towards figuring out why this happens.

2017-07-26 12:59 UTC, vishalya commented
If this looks good, then I can merge it on to blp_dev.

2017-07-26 13:02 UTC, gfiorav commented on app/models/visualization/member.rb
> +                                "user doesn't exist for visualization #{self.name}: #{self.id}")
This logger method supports any hash params after the message. So you can:

```ruby
CartoDB::Logger.error(message: ..., visualisation: visualisation)
```

This is useful since the error message won't change, helping you group. Also, if you use Rollbar (which is already supported by CARTO), this grouping happens automatically. 

You won't loose the other info, it's still logged.

2017-07-26 13:32 UTC, vmanohar1 commented
Will review @vishalya

2017-07-26 13:43 UTC, vmanohar1 commented
Looks ok..

2017-07-26 14:09 UTC, vishalya commented on app/models/visualization/member.rb
> +                                "user doesn't exist for visualization #{self.name}: #{self.id}")
cool. changed it.

2017-07-26 14:27 UTC, tylerparsons approved these changes
Changes look good to me.  This is to prevent failures whenever orphaned visualization records are queried as related tables of of existing visualizations which are to be synchronized.  As a separate task, I'll look into researching and cleaning up the cause of the underlying data issue.

2017-07-26 14:31 UTC, gfiorav commented
+1 @tylerparsons finding the underlying issue is important (might be hiding a more serious problem)

2017-09-07 19:11 UTC, mbektash approved these changes
code changes look good but silencing these functions for erroneous inputs may conceal the root cause of error for untested failure cases. a crash that would happen in the future may consume lots of time to debug even though it happens due to same reason.

2017-09-28 14:16 UTC, merged