Prevent unwanted deletions during lazy load
bloomberg/cartodb pull request #200
Opened 2017-07-21 11:44 UTC by tylerparsons

This change prevents inadvertent deletion of all user remotes when attempting to load common data for a single dataset.  In general, whether for all datasets or for a single dataset, the intended behavior of load common data is as follows:

* Query all user remote datasets of interest
* Query all common data datasets of interest
* For each common data dataset:
  * If a user remote with the same name as the  exists, update it
  * Else, insert a new copy of the common data dataset as a user remote
* Delete each user remote not present in the set of common data datasets

When this implementation was modified to support load common data for just a single dataset, the query for common data datasets was updated to apply the single dataset filter, but the query for user remotes was not.  As a result, the deletion step would delete every user remote except for the one that was being loaded.  This operation was quite costly and could often result in response times of over 20s.

To avoid reimplementation of the extensive logic within this function, this is a surgical change to correctly apply the user remote filter and use the load common data as before.

2017-07-21 13:10 UTC, gfiorav requested changes
Left some comments

2017-07-21 13:10 UTC, gfiorav commented on app/services/visualization/common_data_service.rb
> +      def self.build_url(controller, visualization_name = nil)
minor: 

If the default is null, why not just:

```ruby
def self.build_url(controller, visualisation_name)
```

If you want to avoid passing in null (I agree with that) then use named params:
```ruby
def self.build_url(controller, visualization_name: nil)
```

2017-07-21 13:10 UTC, gfiorav commented on lib/cartodb/url_utils.rb
> +module CartoDB
common practice for new stuff is to place this in `lib/carto/` and namespace `Carto::UrlUtils`.

2017-07-21 13:10 UTC, gfiorav commented on lib/cartodb/url_utils.rb
> +      CGI.parse(URI.parse(url).query)
consider returning `.with_indifferent_access` so that the hash will make no distinction between `key` or `:key`.

2017-07-21 13:10 UTC, gfiorav commented on lib/cartodb/url_utils.rb
> +    module_function :get_url_params
Any particular reason you avoided `def self.get_url_params(url)`? (curious)

2017-07-21 13:10 UTC, gfiorav commented on app/services/visualization/common_data_service.rb
> +        visualization_name_filter = CartoDB::UrlUtils::get_url_param(visualizations_api_url, 'q')
Calling methods from methods like this is deprecated. Use:

```ruby
CartoDB::UrlUtils.get_url_param(...)
```

2017-07-21 13:10 UTC, gfiorav commented on app/services/visualization/common_data_service.rb
> +          ) + visualization_name_filter
I suggest you look into `URI.join`, since it will take care of trailing `/`.

2017-07-21 13:10 UTC, gfiorav commented on lib/cartodb/url_utils.rb
> +end
Missing EOF line

Good job on extracting this. There's a nice opportunity to test it:

```ruby
# in spec/lib/cartodb/url_utils_spec.rb

require_relative '../../spec_helper'

describe(CartoDB::UrlUtils) do
  describe('#get_url_params') do
    it 'handles malformed urls' do
      expect(CartoDB::UrlUtils.get_url_params('foo').to not_raise
    end

    ...
  end
end
```

2017-07-21 13:12 UTC, vishalya commented on lib/cartodb/url_utils.rb
> +  module UrlUtils
URL class would be a better option here. so that we can go on adding any more methods on to it.

2017-07-21 14:27 UTC, tylerparsons commented on lib/cartodb/url_utils.rb
> +    module_function :get_url_params
The method should be static, as I don't think there's a use case for keeping get_url_params as a class method (e.g.like class Foo include UrlsUtils) which self allows.  But I'm fine with either approach - whichever you think is more idiomatic.

2017-07-21 14:30 UTC, tylerparsons commented on lib/cartodb/url_utils.rb
> +  module UrlUtils
Like a wrapper class for a url, which would provide instance methods instead of static methods? Or just a different name for the module?

2017-07-21 14:32 UTC, tylerparsons commented
The comments raise some good points.  I'll make updates accordingly.

2017-07-21 14:46 UTC, vishalya commented on lib/cartodb/url_utils.rb
> +  module UrlUtils
URL as it's own class with private member for the cgi / uri objects.

2017-07-21 14:55 UTC, tylerparsons commented on app/services/visualization/common_data_service.rb
> +          ) + visualization_name_filter
I just realized I probably shouldn't be concatenating at all - the params should be `{type: 'table', privacy: 'public', user_domain: nil, q: visualization_name}` when the name is present otherwise they should be `{type: 'table', privacy: 'public', user_domain: nil}`.

2017-07-21 15:25 UTC, tylerparsons commented on lib/cartodb/url_utils.rb
> +end
@gfiorav Agree with the addition of the test, I'll write those as well.  If we go with what @vishalya suggested, maybe we should raise an exception if they pass an invalid url string. I imagine a lot of the methods a url helper would provide should not be expected to handle invalid urls, though `get_url_params` could.

2017-07-24 21:30 UTC, tylerparsons commented
Received verbal approval fro @vishalya and @mbektas.

2017-07-24 21:30 UTC, merged

2017-07-25 10:16 UTC, gfiorav commented on spec/lib/carto/url_spec.rb
> +module Carto
Kudos, nice test suit!