Rdsimaps3299 fix shared dataset description
bloomberg/cartodb pull request #251
Opened 2018-02-02 20:24 UTC by bb-acarrera

This resolves the issue where newly connected datasets (via Save As) have the description of the "shared_empty_dataset" instead of their own description.

@gfiorav for review as well.

2018-02-05 12:54 UTC, vmanohar1 commented on app/models/table_registrar.rb
> +          if visualization && visualization.name == table.name
Will it be better to have another if check for - "visualization.name == table.name" if visualization exists??

2018-02-05 13:17 UTC, vmanohar1 commented on app/models/table/user_table.rb
> +          if visualization && (visualization.name == self.name || is_first)
Should we have visualization check first and then have the other condition check?

2018-02-05 13:22 UTC, vmanohar1 commented
@mbektas, can you review the unit test changes?

I did review other code changes.

2018-02-06 16:52 UTC, mbektas commented on app/models/table/user_table.rb
> +          if visualization
it will be better if you could make one line

2018-02-07 14:52 UTC, gfiorav requested changes
I left some comments!

The test is on point, kudos for that!

2018-02-07 14:52 UTC, gfiorav commented on app/models/table/user_table.rb
> +    if( !edi.nil? && edi.length > 1 )
No `()` in ruby!

You can also write this as:

```ruby
if edi && edi.any?
  ...
end
```

I recommend you install `rubocop` as a linter. This project already contains some styling files that talk to rubocop :) It will call out these little things for me!

2018-02-07 14:52 UTC, gfiorav commented on app/models/table/user_table.rb
> +            vis = visualization
Instead of carrying `vis`, just return it at this point! That way you don't need an extra variable.

2018-02-07 14:52 UTC, gfiorav commented on app/models/table/user_table.rb
> +      edi.each do |external_data_import|
Maybe you could use `.select` for this?

2018-02-07 20:30 UTC, bb-acarrera commented on app/models/table/user_table.rb
> +    if( !edi.nil? && edi.length > 1 )
Will remove the `()`.  However the .any? will return true if any element exists in the array.  I want to explicitly run my code only if it's greater than 1.

2018-02-07 20:48 UTC, bb-acarrera commented on app/models/table/user_table.rb
> +            vis = visualization
We don't immediately return because there are two possible return values for vis:
1) If the visualization name matches
2) If we are the first visualization if there are NO name matches

In the event of the second one we only want to return the first visualization if we already determined that there are no name matches.  Therefore we cannot exit the loop prematurely.

2018-02-08 17:55 UTC, gfiorav commented on app/connectors/importer.rb
> +        elsif result.schema != ORIGIN_SCHEMA &&
IMHO these conditions are on the "too lengthy" side of things. Any chance you could make them more vertically stacked and not so nested? I think it would improve readability (aka maintainability) :)

2018-02-08 18:52 UTC, bb-acarrera commented on app/connectors/importer.rb
> +        elsif result.schema != ORIGIN_SCHEMA &&
By "Vertically Stacked" do you mean separate if statements?  Typically I thought nested is more favored over multiple indents of multiple if statements?

2018-02-08 19:06 UTC, gfiorav commented on app/connectors/importer.rb
> +        elsif result.schema != ORIGIN_SCHEMA &&
Yes, I meant in seppearte lines. It's a tradeoff...

What does rubocop say?

2018-02-08 21:09 UTC, bb-acarrera commented on app/connectors/importer.rb
> +        elsif result.schema != ORIGIN_SCHEMA &&
Rubocop only complains about the line length.  I have pushed a change to satisfy it.  However it did not comment on nested ifs.

2018-02-09 15:37 UTC, gfiorav reviewed
Added some more comments!

2018-02-09 15:37 UTC, gfiorav commented on .rubocop.yml
> +  Enabled: false
This file is now the same as carto master?

2018-02-09 15:37 UTC, gfiorav commented on spec/connectors/importer_spec.rb
> +    end
Just do the FactoryGirl thing always... it works for both cases!

2018-02-09 16:37 UTC, bb-acarrera commented on .rubocop.yml
> +  Enabled: false
Yes with one minor change to allow rubocop to load it.

2018-02-09 16:55 UTC, gfiorav reviewed
Just some minor comments

2018-02-09 16:55 UTC, gfiorav commented on app/models/table/user_table.rb
> +    if( !edi.nil? && !edi.empty?)
This is the same as

```ruby
unless edi.present?
```

2018-02-09 19:19 UTC, bb-acarrera commented on app/models/table/user_table.rb
> +    if( !edi.nil? && !edi.empty?)
Old revision.  We need to make sure there is more than one element in the array.  Therefore it is now `!edi.nil? && edi.length > 1`

2018-02-15 11:51 UTC, gfiorav approved these changes
VERY nice testing!!

I added a very small comment, just in case it's a typo. Kudos, great job!

2018-02-15 11:51 UTC, gfiorav commented on app/models/table/user_table.rb
> +    if !edi.nil? && edi.length > 1
Just curious: you don't want to enter if `edi` is 1 char long?

2018-02-15 11:51 UTC, gfiorav commented on spec/factories/visualizations.rb
> +  factory :remote_visualization, class: CartoDB::Visualization::Member do
<3

2018-02-15 12:45 UTC, bb-acarrera commented on app/models/table/user_table.rb
> +    if !edi.nil? && edi.length > 1
Correct.  If it's only 1 record then we want to fall back to the old logic.  Based on review it was deemed easier to read for maintainability this way.

2018-02-15 12:49 UTC, merged