Rdsimaps 3346 sample map link copy link
bloomberg/cartodb pull request #279
Opened 2018-02-28 16:40 UTC by bb-acarrera

Exposes "Copy Link" button on Sample Maps.

2018-03-01 16:02 UTC, vishalya requested changes

2018-03-01 16:02 UTC, vishalya commented on lib/assets/javascripts/cartodb/public_common/sample_settings_view.js
> +        <div class="u-inner">
Please separate out the html code into an ejs and then render, if this code is going to be extended in future.

2018-03-01 19:30 UTC, bb-acarrera commented
Updated to use template.  Please re-review.  Thanks.

2018-03-01 19:41 UTC, vishalya commented
Looks good.

2018-03-07 19:42 UTC, vishalya commented on lib/assets/javascripts/cartodb/public_common/sample_settings_view.js
> +    var range = document.createRange();
js-bbg-link selector sounds very generic, what will happen if there are more than 1 on the page? Will that condition happen?

2018-03-07 19:46 UTC, bb-acarrera commented on lib/assets/javascripts/cartodb/public_common/sample_settings_view.js
> +    var range = document.createRange();
If there's more than one I think it becomes ambiguous what will be copied.  Although I don't think anyone else will use it in this popup I can change it to be js-bbg-sample-link

2018-03-08 12:59 UTC, merged